### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by sananth12** [delta/mailer#3]
Add unit tests.

I suggest pyUnit framework + nose test runner.

**Comment by ssundarraj** [comment]
+1

**Comment by thakkarparth007** [comment]
Unit tests for the core functionality is already added. The unit tests cover the campaign.py and mail.py files. The mailer.py file's functionality is indirectly tested by testing the functionality of campaign.py, since the code in that file merely does the sending of a mail. We're already testing campaign.py for that.

The main.py isn't covered however, yet. @Spockuto has authored that file.
