### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by sananth12** [delta/mailer#9]
Please add a continuous integration service. Continuous integration can help catch bugs by running tests automatically.

https://travis-ci.org/ is great for github projects. This will help anyone interested know if the current build is broken or passing the tests.

**Comment by ssundarraj** [comment]
@thakkarparth007 Can you start working on this?

**Comment by thakkarparth007** [comment]
Yes, I had looked into it a couple of days back. Found it a bit complicated. I'll start looking into it again. :P

**Comment by thakkarparth007** [comment]
@ssundarraj, I talked to @sananth12 regarding this. There is one issue I'm facing. I am using mailtrap.io as the test SMTP server. So, there are some credentials involved. When I'm testing locally, there isn't any problem, as the credentials aren't exposed to anyone anyway. To use travis-ci, I can set those credentials as encrypted environment variables, (so that the test script can load them when it's being run). But the problem with that is that travis-ci doesn't expose encrypted environment variables to pull requests. So basically, it won't help in testing any pull requests. But that is the workflow we're currently following.

Ananth asked me to defer the integration of Travis for now.

**Comment by ssundarraj** [comment]
@thakkarparth007 Alright. 
Leaving this issue open for now. We will get to it later.

**Comment by vigneshmanix** [comment]
Instead of using mailtrap.io , provision a vagrant environment, install postfix there and test with received emails 
@Spockuto can help with this.

**Comment by thakkarparth007** [comment]
There was an alternative that I was thinking of. While going through the code of the Envelopes module, I saw their test code. They had simply stubbed the python's email module and the testing was done marvelously. I think this should be fool-proof and automated.
